AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MyHomeBar - Personal Bartender Recommendation System

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        INVENTORY_TABLE: !Ref InventoryTable
        RECIPES_TABLE: !Ref RecipesTable
        IMAGES_BUCKET: !Ref RecipeImagesBucket
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Tables
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyHomeBar-Inventory
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyHomeBar-Recipes
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: S
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # API Gateway
  MyHomeBarApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions
  InventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyHomeBar-Inventory
      CodeUri: ../backend/
      Handler: src/functions/inventory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
      Events:
        GetInventory:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory
            Method: GET
        GetInventoryItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory/{id}
            Method: GET
        CreateInventoryItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory
            Method: POST
        UpdateInventoryItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory/{id}
            Method: PUT
        DeleteInventoryItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory/{id}
            Method: DELETE
        GetExpiringItems:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /inventory/expiring
            Method: GET

  RecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyHomeBar-Recipes
      CodeUri: ../backend/
      Handler: src/functions/recipes.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RecipesTable
      Events:
        GetRecipes:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recipes
            Method: GET
        GetRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recipes/{id}
            Method: GET
        CreateRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recipes
            Method: POST
        UpdateRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recipes/{id}
            Method: PUT
        DeleteRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recipes/{id}
            Method: DELETE

  RecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyHomeBar-Recommendations
      CodeUri: ../backend/
      Handler: src/functions/recommendations.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InventoryTable
        - DynamoDBReadPolicy:
            TableName: !Ref RecipesTable
      Events:
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /recommendations
            Method: POST

  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyHomeBar-ImageUpload
      CodeUri: ../backend/
      Handler: src/functions/imageUpload.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RecipeImagesBucket
      Events:
        GetUploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref MyHomeBarApi
            Path: /images/upload-url
            Method: POST

  # S3 Bucket for Frontend Hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'myhomebar-frontend-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # S3 Bucket for Recipe Images
  RecipeImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'myhomebar-images-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  RecipeImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RecipeImagesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${RecipeImagesBucket.Arn}/*'

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyHomeBarApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: MyHomeBar-ApiEndpoint

  FrontendBucketName:
    Description: "S3 bucket for frontend hosting"
    Value: !Ref FrontendBucket
    Export:
      Name: MyHomeBar-FrontendBucket

  FrontendUrl:
    Description: "Frontend website URL"
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: MyHomeBar-FrontendUrl

  RecipeImagesBucketName:
    Description: "S3 bucket for recipe images"
    Value: !Ref RecipeImagesBucket
    Export:
      Name: MyHomeBar-ImagesBucket

  InventoryTableName:
    Description: "DynamoDB Inventory Table"
    Value: !Ref InventoryTable

  RecipesTableName:
    Description: "DynamoDB Recipes Table"
    Value: !Ref RecipesTable
